micronaut:
  application:
    name: mattermostBots
netty:
  default:
    allocator:
      max-order: 3

jackson:
  module-scan: false
  deserialization:
    READ_DATE_TIMESTAMPS_AS_NANOSECONDS: false
flyway:
  enabled: true
  datasources:
    default:
      enabled: true
      validate-on-migrate: false # https://github.com/flyway/flyway/issues/3431
db:
  file: ./data/mmbots
datasources:
  default:
    url: 'jdbc:h2:${db.file}'
    driver-class-name: org.h2.Driver
    username: sa
    password: ''
    maximum-pool-size: 2
    minimumIdle: 0
r2dbc:
  datasources:
    default:
      url: r2dbc:h2:file:///${db.file}
      username: sa
      password: ''
jooq:
  r2dbc-datasources:
    default:
      sql-dialect: H2

webhook:
  base-url:
  commands:
    - trigger: group-create
      auto-complete-hint: 'groupname'
      auto-complete-desc: 'Creates new group'
      display-name: 'group-create'
      description: 'Creates a new group'
    - trigger: group-delete
      auto-complete-hint: "yes i'm sure i want to delete @groupname"
      auto-complete-desc: 'Deletes group'
      display-name: 'group-delete'
      description: 'Deletes a group'
    - trigger: group-edit
      auto-complete-hint: '@groupname (add|remove) @username1 @username2 @username3'
      auto-complete-desc: 'Add or remove users to/from group @groupname'
      display-name: 'group-edit'
      description: 'Add or remove users to/from group'
    - trigger: group-info
      auto-complete-hint: '@groupname [optionally]'
      auto-complete-desc: 'Show info about all groups or specific group @groupname'
      display-name: 'group-info'
      description: 'Show info about groups'
    - trigger: random
      auto-complete-hint: '@groupname [optionally] and text to tell to selected user'
      auto-complete-desc: 'Select random user from group or from current channel, if groupname was not specified'
      display-name: 'random'
      description: 'Select random user'
    - trigger: invite-all-except
      auto-complete-hint: '@username'
      auto-complete-desc: "Add all users to the current channel except those specified in the command's input"
      display-name: 'invite-all-except'
      description: "Add all users to the current channel except those specified in the command's input"
    - trigger: on-duty
      auto-complete-hint: '[@username1, [@username2] | nobody] for <keyword>'
      auto-complete-desc: "Makes you or selected users to be on duty for some <keyword>"
      display-name: 'on-duty'
      description: "Makes you or selected users to be on duty for some <keyword>"

mattermost:
  base-url:
  auth:
    token: